# Copyright 2018-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

steps:

  - label: ":docker: Build"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_BUILDKIT: "1"
    command:
      >
        docker build \
          --progress=plain \
          --file tools/docker/Dockerfile \
          --target firecracker-containerd-unittest \
          --tag localhost/firecracker-containerd-unittest:${BUILDKITE_BUILD_NUMBER} .

        docker build \
          --progress=plain \
          --file tools/docker/Dockerfile \
          --target firecracker-containerd-unittest-nonroot \
          --tag localhost/firecracker-containerd-unittest-nonroot:${BUILDKITE_BUILD_NUMBER} .

  - wait

  - label: ":rotating_light: snapshotter root tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    artifact_paths:
      - "logs/*"
    command:
      >
        mkdir $(pwd)/logs
        && docker run --rm \
          --privileged \
          --volume /dev:/dev \
          --volume /sys:/sys \
          --volume /run/udev/control:/run/udev/control \
          --volume $(pwd)/logs:/var/log/firecracker-containerd-test \
          --ipc=host \
          localhost/firecracker-containerd-unittest:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/snapshotter
            make test EXTRAGOARGS="-v -count=1"
          '

  - label: ":hammer: snapshotter tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    command:
      >
        docker run --rm \
          localhost/firecracker-containerd-unittest-nonroot:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/snapshotter
            DISABLE_ROOT_TESTS='true' make test EXTRAGOARGS="-v -count=1"
          '

  - label: ":running_shirt_with_sash: runtime tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    artifact_paths:
      - "logs/*"
    command:
      >
        mkdir $(pwd)/logs
        && docker run --rm \
          --privileged \
          --volume /dev:/dev \
          --volume /sys:/sys \
          --volume /run/udev/control:/run/udev/control \
          --volume $(pwd)/logs:/var/log/firecracker-containerd-test \
          --ipc=host \
          localhost/firecracker-containerd-unittest:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/runtime
            make test EXTRAGOARGS="-v -count=1"
          '
