# Copyright 2018-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"). You may
# not use this file except in compliance with the License. A copy of the
# License is located at
#
# 	http://aws.amazon.com/apache2.0/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

steps:

  - label: ":docker: Build"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    env:
      DOCKER_BUILDKIT: "1"
    command:
      >
        docker build \
          --progress=plain \
          --file tools/docker/Dockerfile \
          --target firecracker-containerd-unittest \
          --tag localhost/firecracker-containerd-unittest:${BUILDKITE_BUILD_NUMBER} .

        docker build \
          --progress=plain \
          --file tools/docker/Dockerfile \
          --target firecracker-containerd-unittest-nonroot \
          --tag localhost/firecracker-containerd-unittest-nonroot:${BUILDKITE_BUILD_NUMBER} .

        docker build \
          --progress=plain \
          --file tools/docker/Dockerfile \
          --target firecracker-containerd-e2etest-naive \
          --tag localhost/firecracker-containerd-e2etest-naive:${BUILDKITE_BUILD_NUMBER} .

  - wait

  # Git history validation happens after the 'wait' step so it happens
  # in parallel with the subsequent tests and does not prevent them
  # from running in the event of a validation failure.
  - label: 'git log validation'
    command: './.buildkite/logcheck.sh'

  - label: ":rotating_light: :hammer: snapshotter *root* tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    artifact_paths:
      - "logs/*"
    command:
      >
        docker run --rm \
          --privileged \
          --volume /dev:/dev \
          --volume /sys:/sys \
          --volume /run/udev/control:/run/udev/control \
          --ipc=host \
          localhost/firecracker-containerd-unittest:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/snapshotter
            make test EXTRAGOARGS="-v -count=1"
          '

  - label: ":hammer: snapshotter tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    command:
      >
        docker run --rm \
          localhost/firecracker-containerd-unittest-nonroot:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/snapshotter
            DISABLE_ROOT_TESTS='true' make test EXTRAGOARGS="-v -count=1"
          '

  - label: ":running_shirt_with_sash: runtime unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    artifact_paths:
      - "logs/*"
    command:
      >
        docker run --rm \
          --privileged \
          --volume /dev:/dev \
          localhost/firecracker-containerd-unittest:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/runtime
            make test EXTRAGOARGS="-v -count=1"
          '

  - label: ":rotating_light: :running_shirt_with_sash: runtime isolated tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    artifact_paths:
      - "logs/*"
    env:
      FCCD_PACKAGE_DIR: "runtime"
      FCCD_TESTNAME_REGEX: "_Isolated"
    command:
      >
        mkdir $(pwd)/logs
        && .buildkite/run-tests-by-name-regex.sh \
          "--privileged \
          --volume /dev:/dev \
          --volume /sys:/sys \
          --volume /run/udev/control:/run/udev/control \
          --volume $(pwd)/logs:/var/log/firecracker-containerd-test \
          --ipc=host \
          --env ENABLE_ISOLATED_TESTS=1" \
          "localhost/firecracker-containerd-e2etest-naive:${BUILDKITE_BUILD_NUMBER}"

  - label: ":fencer: agent tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    artifact_paths:
      - "logs/*"
    command:
      >
        mkdir $(pwd)/logs
        && docker run --rm \
          --privileged \
          --volume /dev:/dev \
          --volume /sys:/sys \
          --volume /run/udev/control:/run/udev/control \
          --volume $(pwd)/logs:/var/log/firecracker-containerd-test \
          --ipc=host \
          localhost/firecracker-containerd-unittest:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/agent
            make test EXTRAGOARGS="-v -count=1"
          '

  - label: ":exclamation: event tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
    command:
      >
        docker run --rm \
          localhost/firecracker-containerd-unittest-nonroot:${BUILDKITE_BUILD_NUMBER} \
          '
            cd /firecracker-containerd/eventbridge
            make test EXTRAGOARGS="-v -count=1"
          '
