name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      GO111MODULE: on

    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04']
        go: ['1.13', '1.14', '1.15', '1.16', '1.17']
      # Build all variants regardless of failures
      fail-fast: false

    name: ${{ matrix.os }} / Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          # By default, the checkout action only fetches the last commit,
          # but we want to run DCO check against all commit messages.
          # Assuming that a pull request may have multiple commits,
          # fetching the single commit doesn't work for us.
          #
          # While DCO check (on Makefile) checks latest 20 commits,
          # the checkout action automatically creates a merge commit
          # for merging "main" into a pull request branch.
          # In addition to that, Git cannot recognize merge commits when
          # one of the parents is missing.
          # So, we will fetch 30 commits just in case to have
          # 20 actual commits with associated merged commits.
          fetch-depth: 30
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: make deps
      - run: make
      - run: make lint
      - run: make test
      - run: |
          make tidy
          git diff --exit-code
        # The result of "go mod tidy" is different since Go 1.16.
        # We will use the old result until we update BuildKite and other environments.
        if: matrix.go < '1.16'
      - run: |
          make proto
          git diff --exit-code
